/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns.h"


CLIENT *
dns_1(char *host)
{
	CLIENT *clnt = clnt_create (host, 0x20000001, DNSv1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	return clnt;
}


int
main (int argc, char *argv[])
{
	if (argc < 3) {
		printf ("usage: %s <server host> <operation>\n", argv[0]);
		exit (1);
	}

	CLIENT *clnt = dns_1 (argv[1]);

	if(strcmp(argv[2], "consultar") == 0) {
		if(argc < 4) {
			printf("usage: %s <server host> consultar <nombre>\n", argv[0]);
			exit(1);
		}

		respuesta *res = consultar_1(argv[3], clnt);
		if(res->errno == 0) {
			printf("With name %s, found IP %s\n", argv[3], res->respuesta_u.cadena);
		} else {
			printf("With name %s, no IP found (errno %d)\n", argv[3], res->errno);
		}
	}

	if(strcmp(argv[2], "registrar") == 0) {
		if(argc < 5) {
			printf("usage: %s <server host> registrar <nombre> <ip>\n", argv[0]);
			exit(1);
		}

		printf("> %s %s %s\n", "registrar", argv[3], argv[4]);
		int *res = registrar_1(argv[3], argv[4], clnt);
		if(*res == 0) {
			printf("With name %s, registered IP %s\n", argv[3], argv[4]);
		} else {
			printf("Couldn't register IP %s (errno %d)\n", argv[4], *res);
		}
	}
	
	if((strcmp(argv[2], "liberar") == 0)) {
		if(argc < 4) {
			printf("usage: %s <server host> liberar <nombre>\n", argv[0]);
			exit(1);
		}

		int *res = liberar_1(argv[3], clnt);
		if(*res == 0) {
			printf("With name %s, IP was freed\n", argv[3]);
		} else {
			printf("Name %s was not freed (errno %d)\n", argv[3], *res);
		}
	}

	clnt_destroy(clnt);
}
