/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linkedlist.h"
#include "dns.h"

#define DNSID_TL 0x20000001
#define DNSID_C1 0x20000002
#define DNSID_C2 0x20000003

#define DNSMAME_TL "red1"
#define DNSMAME_C1 "red2"
#define DNSMAME_C2 "red3"

// Utility for grouped strings on 
typedef struct _dotstring {
	char top[256];
	char sub[256];
} dotstring_t;

void decompose(dotstring_t *res, const char *str) {
	char buf[256];
	strcpy(buf, str);

  int dot_pos = strchr(str, '.') - str;
  buf[dot_pos] = '\0';

  strcpy(res->top, buf);
  strcpy(res->sub, buf + dot_pos + 1);
}

struct LinkedList iptable;

respuesta *
consultar_1_svc(char *name,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static respuesta  result = { .errno = -1 };

	printf("Requested '%s(%s)' on %#lx\n", "consultar", name, DNSID);

	// If there's data
	if(iptable.head != NULL) {
		// Look-up by name
		const char *ip = LinkedList_FindByName(&iptable, name);

		// Return IP found
		if(ip != NULL) {
			result.errno = 0;
			strcpy(result.respuesta_u.cadena, ip);
			return &result;
		}
	}

	// If top-level DNS, delegate
	if(DNSID == DNSID_TL) {
		CLIENT *clnt;
		respuesta *res;

		// Sub-DNS 1
		clnt = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if (clnt != NULL) {
			
			res = consultar_1(name, clnt);
			if (res != NULL && res->errno == 0) {
				result.errno = res->errno;
				strcpy(result.respuesta_u.cadena, res->respuesta_u.cadena);
				return &result;
			}
		}

		// Sub-DNS 2
		clnt = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if (clnt != NULL) {
			
			res = consultar_1(name, clnt);
			if (res != NULL && res->errno == 0) {
				result.errno = res->errno;
				strcpy(result.respuesta_u.cadena, res->respuesta_u.cadena);
				return &result;
			}
		}

		clnt_destroy(clnt);
	}

	// If not found, return an error
	result.errno = -1;
	return &result;
}

int *
registrar_1_svc(char *name, char *req_ip,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static int  result = -1;

	printf("Requested '%s(%s, %s)' on %#lx\n", "registrar", name, req_ip, DNSID);

	dotstring_t dotstr;
	decompose(&dotstr, req_ip);

	u_long v = (atol(dotstr.top) | 0x20000000);
	// Check if this registrar is responsable for requested IP
	if(DNSID == v) {
		printf("Registering %s - %s\n", name, req_ip);
		// If there's data
		if(iptable.head == NULL) {
			printf("Starting new data\n");
			iptable.head = Node_New(name, req_ip);
		} else {
			printf("There's already data\n");
			// Check if IP is already registered
			if(LinkedList_FindByName(&iptable, name) != NULL) {
				result = -1;
				return &result;
			}

			LinkedList_Append(&iptable, name, req_ip);
		}

		result = 0;
		return &result;
	} 
	// Delegate responsability if top-level DNS
	else if(DNSID == DNSID_TL) {
		CLIENT *clnt;
		int *res;

		// Sub-DNS 1
		clnt = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if (clnt != NULL) {
			
			res = registrar_1(name, req_ip, clnt);
			if (res != NULL && *res == 0) {
				result = *res;
				return &result;
			}
		}

		// Sub-DNS 2
		clnt = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if (clnt != NULL) {
			
			res = registrar_1(name, req_ip, clnt);
			if (res != NULL && *res == 0) {
				result = *res;
				return &result;
			}
		}

		clnt_destroy(clnt);
	}

	// No-ones responsability to register, fail
	result = -1;
	return &result;
}

int *
liberar_1_svc(char *name,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static int  result = -1;

	printf("Requested '%s(%s)' on %#lx\n", "liberar", name, DNSID);

	// Check if name is available locally
	if(iptable.head != NULL) {
		// Look-up by name
		const char *ip = LinkedList_FindByName(&iptable, name);

		// Delete node if found
		if(ip != NULL) {
			LinkedList_Delete(&iptable, name);
			result = 0;
			return &result;
		}
	}
	
	// Delegate responsability if top-level DNS
	if(result != 0 && DNSID == DNSID_TL) {
		CLIENT *clnt;
		int *res;

		// Sub-DNS 1
		clnt = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if (clnt != NULL) {
			res = liberar_1(name, clnt);
			if (res != NULL && *res == 0) {
				result = *res;
				return &result;
			}
		}

		clnt_destroy(clnt);

		// Sub-DNS 2
		clnt = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if (clnt != NULL) {
			res = liberar_1(name, clnt);
			if (res != NULL && *res == 0) {
				result = *res;
				return &result;
			}
		}

		clnt_destroy(clnt);
	}

	return &result;
}