/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linkedlist.h"
#include "dns.h"

#define DNSID_TL 0x20000001
#define DNSID_C1 0x20000002
#define DNSID_C2 0x20000003

#define DNSMAME_TL "red1"
#define DNSMAME_C1 "red2"
#define DNSMAME_C2 "red3"

// Utility for grouped strings on 
typedef struct _dotstring {
	char top[256];
	char sub[256];
} dotstring_t;

void decompose(dotstring_t *res, const char *str) {
	char buf[512];
	strcpy(buf, str);

  char *dotptr = strchr(buf, '.');
  *dotptr = '\0';

  strcpy(res->top, buf);
  strcpy(res->sub, dotptr + 1);
}

struct LinkedList iptable = {};

CLIENT *clnt1, *clnt2;

respuesta *
consultar_1_svc(char *name,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static respuesta  result = { .errno = -1 };

	printf("Requested '%s(%s)' on %#lx\n", "consultar", name, DNSID);

	// If there's data
	if(iptable.head != NULL) {
		// Look-up by name
		const char *ip = LinkedList_FindByName(&iptable, name);

		// Return IP found
		if(ip != NULL) {
			result.errno = 0;
			result.respuesta_u.cadena = ip;
			return &result;
		}
	}

	// If top-level DNS, delegate
	if(DNSID == DNSID_TL) {
		respuesta *res;

		// Sub-DNS 1
		if(clnt1 == NULL) clnt1 = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if (clnt1 != NULL) {
			res = consultar_1(name, clnt1);
			if (res != NULL && res->errno == 0) {
				result.errno = res->errno;
				result.respuesta_u.cadena = res->respuesta_u.cadena;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);

		// Sub-DNS 2
		if(clnt2 == NULL) clnt2 = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if (clnt2 != NULL) {
			res = consultar_1(name, clnt2);
			if (res != NULL && res->errno == 0) {
				result.errno = res->errno;
				result.respuesta_u.cadena = res->respuesta_u.cadena;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);
	}

	// If not found, return an error
	result.errno = -1;
	return &result;
}

int *
registrar_1_svc(char *name, char *req_ip,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static int  result = -1;

	printf("Requested '%s(%s, %s)' on %#lx\n", "registrar", name, req_ip, DNSID);

	dotstring_t dotstr;
	decompose(&dotstr, req_ip);

	// Check if this registrar is responsable for requested IP
	if(DNSID == (u_long)(atol(dotstr.top) | 0x20000000)) {
		// If there's data
		if(iptable.head == NULL) {
			iptable.head = Node_New(name, req_ip);
		} else {
			// Check if IP is already registered
			if(LinkedList_FindByName(&iptable, name) != NULL) {
				result = -1;
				return &result;
			}

			LinkedList_Append(&iptable, name, req_ip);
		}

		result = 0;
		return &result;
	} 
	// Delegate responsability if top-level DNS
	else if(DNSID == DNSID_TL) {
		int *res;

		// Sub-DNS 1
		if(clnt1 == NULL) clnt1 = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if(clnt1 != NULL) {
			
			res = registrar_1(name, req_ip, clnt1);
			if (res != NULL && *res == 0) {
				result = *res;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);

		// Sub-DNS 2
		if(clnt2 == NULL) clnt2 = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if(clnt2 != NULL) {
			
			res = registrar_1(name, req_ip, clnt2);
			if (res != NULL && *res == 0) {
				result = *res;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);
	}

	// No-ones responsability to register, fail
	result = -1;
	return &result;
}

int *
liberar_1_svc(char *name,  struct svc_req *rqstp)
{
	const u_long DNSID = rqstp->rq_prog;
	static int  result = -1;

	printf("Requested '%s(%s)' on %#lx\n", "liberar", name, DNSID);

	// Check if name is available locally
	if(iptable.head != NULL) {
		// Look-up by name
		const char *ip = LinkedList_FindByName(&iptable, name);

		// Delete node if found
		if(ip != NULL) {
			LinkedList_Delete(&iptable, name);
			result = 0;
			return &result;
		}
	}
	
	// Delegate responsability if top-level DNS
	if(DNSID == DNSID_TL) {

		int *res;

		// Sub-DNS 1
		if(clnt1 == NULL) clnt1 = clnt_create ("localhost", DNSID_C1, DNSv1, "udp");
		if (clnt1 != NULL) {
			res = liberar_1(name, clnt1);
			if (res != NULL && *res == 0) {
				result = *res;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);

		// Sub-DNS 2
		if(clnt2 == NULL) clnt2 = clnt_create ("localhost", DNSID_C2, DNSv1, "udp");
		if (clnt2 != NULL) {
			res = liberar_1(name, clnt2);
			if (res != NULL && *res == 0) {
				result = *res;

				// clnt_destroy(clnt);
				return &result;
			}
		}

		// clnt_destroy(clnt);
	}

	return &result;
}